name: CI Pipeline Nginx Docker

# 1. PEMICU (Trigger)
on:
  push:
    branches:
      - main

# 2. DAFTAR PEKERJAAN (Jobs)
jobs:
  build-image-lokal:
    # 3. MESIN PEKERJA (Runner)
    runs-on: ubuntu-latest

    # 4. LANGKAH-LANGKAH KERJA (Steps)
    steps:
      - name: Langkah 1 - Mengambil Kode dari GitHub
        uses: actions/checkout@v4

      - name: Langkah 2 - Mengecek Mesin Docker
        run: docker --version

      - name: Langkah 3 - Merakit (Build) Docker Image
        run: docker build -t web-nginx-saya:latest .

      - name: Langkah 4 - Verifikasi Hasil Build
        run: docker images
