name: Build and Push ke Docker Hub
# 1. PEMICU: Robot menyala saat ada push ke branch main
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    # 2. SERVER PINJAMAN: Menggunakan Linux Ubuntu terbaru
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kode
        uses: actions/checkout@v4
        # Penjelasan: Robot mengunduh file index.html dan Dockerfile-mu ke dalam server

      - name: Login ke Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # Penjelasan: Robot memakai kunci rahasia yang tadi kamu buat untuk masuk ke Docker Hub

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        # Penjelasan: Memasang mesin turbo agar proses pembuatan image lebih cepat

      - name: Build dan Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # PENTING: Ubah 'namamu' dengan username Docker Hub aslimu!
          tags: yanuarr04/belajar-cicd:latest
        # Penjelasan: Robot merakit Dockerfile menjadi Image bernama "web-sederhana", lalu langsung membuangnya (push) ke Docker Hub.
